翻譯
alejoseb/Modbus-STM32-HAL-FreeRTOS pull request #13
Opened 2021-03-27 18:30 UTC by godchadigo

2021-03-27 18:32 UTC, godchadigo commented on MODBUS-LIB/Inc/Modbus.h
> +
功能註解

2021-03-27 23:08 UTC, alejoseb commented on MODBUS-LIB/Inc/Modbus.h
> +
Hi, 
Thanks for your translation  and annotations in Chinese, however I can only maintain this library in English.

I think your annotation is still very important for Chinese speakers. I think I can add a second README file with your translation and you can add your comments and annotation there explaining the fields of the Modbus handler.  
I will be more than happy to add a second README file in Chinese to the master repo.
Meanwhile I will not merge this pull request.

2021-03-28 02:30 UTC, godchadigo commented on README.md
> +* * *
New Translation File .

2021-03-28 17:35 UTC, alejoseb requested changes
Please add a new file for the translation, but do not add the translation at the end of the original Readme file. You can add a link t in the original Readme pointing to the Chinese translation file.  
Also, please remove the Chinese anotations from  Modbus.h, instead you can extend the translation file adding the annotation there.

2021-03-30 15:21 UTC, merged

2021-03-30 15:22 UTC, alejoseb commented
I solved the issues and merged your readme file. Thanks!